---
title: "Reviews"
output: 
  distill::distill_article:
    toc: true
---


## Capsule reviews

"A synthetic and comprehensive work that finely retraces the steps that allowed the construction of a "visual thought". Friendly and Wainer invite us to follow them in a masterly study of the graphic innovations, their context and their scientific use. This brilliant book, without equivalent so far, will be an indispensable read for all those interested in information visualization."
-- **Gilles Palsky, coauthor of _An Atlas of Geographical Wonders_**

"Friendly and Wainer are the Watson and Crick of statistical graphics, showing us the history of the DNA structure that is the code of life for innovative visualizations." 
-- **Ben Shneiderman, founder of the Human-Computer Interaction Lab, University of Maryland**

"Data expertise is a fundamental prerequisite for success in our digital age. But exactly how, and when, have we learned to draw conclusions from data? For decades, Michael Friendly and Howard Wainer have been studying how data has informed decision-making, through visualization and statistical analysis. Replete with mesmerizing visual examples, this book is an eye-opening distillation of their research."
-- **Sandra Rendgen, author of _History of Information Graphics_**

"Michael Friendly and Howard Wainer have given us a wonderful history of the dazzling field of data visualization. They bring new life to ancient death statistics and describe the artistic poetry used to display numbers. An intriguing story of how we have learned to communicate data of all types."
-- **Stephen M. Stigler, author of _The Seven Pillars of Statistical Wisdom_**

"Two of the most distinguished scholars of data visualization give us a glimpse of ancient attempts to quantify the world, before revealing the century-long revolution that led to the invention of modern statistics and many of the graphical methods we use today. I learned a lot from this book, and I think you will too."
-- **Alberto Cairo, author of _How Charts Lie: Getting Smarter about Visual Information_**

"Friendly and Wainer demonstrate the amazing progress that has been made in data graphics over the past two hundred years. Understanding this history-where graphs came from and how they developed-will be valuable as we move forward."
-- **Andrew Gelman, coauthor of _Regression and Other Stories_**

"The invention of graphs and charts was a much quieter affair than that of the telescope, but these tools have done just as much to change how and what we see."
-- **Hannah Fry, _The New Yorker_**

“This is a thoughtful and well-written introduction to the world of data visualization and its history.” -- **Bill Slater, _Mathematical Association of America_**

"The book is a marvel of research scholarship. Unlike histories of the rich and famous, the work of many of the stars of this
narrative is relatively obscure. The authors have done a remarkable job of digging it up
and putting it into perspective in a way that is both clear and accessible. This is the sort of book that one can browse and sample in bitesize chunks as the mood seizes, encountering curious delights while doing so." -- **Bert Gunter, _Significance_**

"What sets this book apart from other such histories is the depth of analysis dedicated to the graphic instruments
of science that emerged out of a need to explore complex issues, identify patterns, and reduce complexity
in communication. Friendly and Wainer dive deep into numerical relationships, providing thoughtful analysis
that highlights the strength of the graphs. And with a retrospective eye, they present critiques and contemporary
alternatives." -- **María del Mar Navarro, _She Ji: The Journal of Design, Economics, and Innovation_**

"This book is a must-read for anyone interested in visualization. Its scope and informed perspective already make it a
classic." -- **Leland Wilkinson, _CHANCE_, 34:4, 38-40, November, 2021.**

"The book covers a wide and varied history in a manner that is remarkably free of technical phrasing and instead applies a common, clear language. That alone is reason enough, these days for praise. ... The book was worth waiting for and I’m delighted to have it on my shelf."
-- **Tom Koch, Author of _Disease Maps_**

"The authors have taken on the ambitious task of writing whirlwind historical narratives, synthesizing centuries of scientific inquiry within a single chapter. Such is this book’s grand ambition: it chronicles the history of graphic communication since the beginning of human language and reflects decades of expertise from the authors, who were themselves part of a prominent wave of visualization research."
-- **Crystal Lee, _Information & Culture_, December, 2021.**

"C'est un passionnant voyage aux côtés de ceux qui ont inventé le langage de la dataviz, du 17e à nos jours,
un ouvrage magistral et accessible"
-- **Éric Mauvière, Twitter**, December 28, 2021.


## More detailed reviews

* [Hannah Fry, _New Yorker_, "When Graphs are a Matter of Life and Death"](https://www.newyorker.com/magazine/2021/06/21/when-graphs-are-a-matter-of-life-and-death), Online: June 14, 2021;
print: June 21, 2021.

* [Annette Gordon-Reed, _New York Review of Books_, "The Color Line"](https://www.nybooks.com/articles/2021/08/19/du-bois-color-line-paris-exposition/), Print: August 19, 2021 issue.

* [George Spencer, _Princeton Alumni Weekly_, "Howard Wainer *68 and Michael Friendly *71 Give Data Meaning"](https://paw.princeton.edu/article/howard-wainer-68-and-michael-friendly-71-give-data-meaning), Published online August 25, 2021.

* [Bill Slater, _Mathematical Association of America_, Review](https://www.maa.org/press/maa-reviews/a-history-of-data-visualization-and-graphic-communication), Online: September 22, 2021.

* [Bert Gunter, _Significance_](pdf/SIGNIFICANCE-Review.pdf), Review in v. **18**(5), p. 45
(Oct. 2021 issue)

* [María del Mar Navarro, _She Ji: The Journal of Design, Economics, and Innovation_](https://www.sciencedirect.com/science/article/pii/S2405872621000873), 
Volume 7, Issue 3, Autumn 2021, Pages 485-491.

* [Nick Cox, Customer review on Amazon](https://www.amazon.com/gp/customer-reviews/R19HUUJRY5UXOY/ref=cm_cr_arp_d_rvw_ttl?ie=UTF8&ASIN=0674975235), September 27, 2021.

* [George Spencer, _Journal of Accountancy_, "Creating the right visuals for your data"](https://www.journalofaccountancy.com/news/2021/oct/tools-building-visual-representations-data.html),
an interview published October 18, 2021.

* [Leland Wilkinson, _CHANCE_, 34:4, 38-40](https://doi.org/10.1080/09332480.2021.2003643), Online: November 21, 2021.

* [Crystal Lee, _Information & Culture](https://infoculturejournal.org/book_reviews/Friendly_Lee), December, 2021.
